In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm,datasets
from sklearn.svm import SVC


In [ ]:
dataset = datasets.load_iris()

In [ ]:
dataset

In [ ]:
# types of kernal
# linear ->if dataset linearly separable , polynomial -> if not much spreaded but not liner


In [ ]:
x=dataset.data[:,:-2]
y=dataset.target

In [ ]:
svc = svm.SVC(kernel='linear',C=1).fit(x,y)

In [ ]:
rbf_svm = svm.SVC(kernel='rbf',C=1,gamma=0.5).fit(x,y)

In [ ]:
poly_svm = svm.SVC(kernel='poly',degree=5,C=1).fit(x,y)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

In [ ]:
y_pred = svc.predict(x)
print("Linear",accuracy_score(y,y_pred))
print("confusion matrix",confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

Linear 0.82
confusion matrix [[50  0  0]
 [ 0 38 12]
 [ 0 15 35]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.72      0.76      0.74        50
           2       0.74      0.70      0.72        50

    accuracy                           0.82       150
   macro avg       0.82      0.82      0.82       150
weighted avg       0.82      0.82      0.82       150



In [ ]:
y_pred = poly_svm.predict(x)
print("polunomial",accuracy_score(y,y_pred))
print("confusion matrix",confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

polunomial 0.7933333333333333
confusion matrix [[50  0  0]
 [ 0 38 12]
 [ 0 19 31]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.67      0.76      0.71        50
           2       0.72      0.62      0.67        50

    accuracy                           0.79       150
   macro avg       0.80      0.79      0.79       150
weighted avg       0.80      0.79      0.79       150



In [ ]:
# macro avg -> direct average
# weightted avg -> after multiplicaiotn with support